apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app-service-monitor
  labels:
    team: frontend
    env: production
spec:
  selector:
    matchLabels:
      app: node-app-service
  endpoints:
  - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
      # env: production
  resources:
    requests:
      memory: 400Mi  
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: Prometheus
# metadata:
#   name: prometheus
# spec:
#   serviceAccountName: prometheus
#   podMonitorSelector:
#     matchLabels:
#       team: frontend
#   resources:
#     requests:
#       memory: 400Mi
#   enableAdminAPI: false     
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    # nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus