apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  template:
    spec:
      containers:
      - name: node-app
        env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: KUBE_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace                                