apiVersion: v1
kind: ConfigMap
metadata:
  name: node-app-config
  labels:
    app: node-app 
data:
  API_HOST: "0.0.0.0"
  API_PORT: "3000"
  NODE_ENV: development
  SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0