apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app 
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'    
    spec:
      containers:
      - name: node-app
        image: cdesch/example-node-app:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: node-app-config          
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "250m"