apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    env: production
spec:
  selector:
    app: node-app 
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
